# Generated by Django 2.2.2 on 2019-06-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('pub_date', models.DateTimeField(null=True)),
                ('body', models.TextField(default=None, max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.TextField(default=None, max_length=50)),
                ('icon', models.ImageField(upload_to='images/')),
                ('vote_totals', models.IntegerField(default=1)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
